[package]
name = "authrust-axum-example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
authrust = { path = "../..", features = ["axum"] }
axum = "0.8.9"
serde_json = "1.0.151"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres"] }
tokio = { version = "1.53.1", features = ["full"] }
